name: Create New User

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Last User ID
        id: get_user_id
        run: |
          FILE="user_id.txt"
          USERS_FILE="users.txt"
          if [[ -f "$FILE" ]]; then
            LAST_ID=$(cat $FILE)
          else
            LAST_ID=0
          fi
          NEW_ID=$((LAST_ID + 1))
          echo "New user ID: $NEW_ID"
          echo "$NEW_ID" > $FILE
          echo "USER_ID=$NEW_ID" >> $GITHUB_ENV
          
          # Store user in users.txt
          echo "User-$NEW_ID: created on $(date)" >> $USERS_FILE

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add user_id.txt users.txt
          git commit -m "Added new user: User-$USER_ID"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
